"""Add user_id to urls.

Revision ID: e5828c5ba8cc
Revises: f33b70fdb0aa
Create Date: 2025-06-02 23:03:15.331001
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e5828c5ba8cc"
down_revision: str | None = "f33b70fdb0aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("urls", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "urls", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "urls", type_="foreignkey")
    op.drop_column("urls", "user_id")
    # ### end Alembic commands ###
